[tool.poetry]
name = "python-sandbox"
version = "0.1.0"
description = ""
authors = ["Soichi Sumi <soichi.sumi@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^6.2.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
